improved handling of errors at configure arguments

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -73,6 +73,9 @@ do
   --prefix=*)
     PREFIX=${arg#--prefix=}
   ;;
+  --bindir=*)
+    SBINDIR=${arg#--bindir=}
+  ;;
   --sbindir=*)
     SBINDIR=${arg#--sbindir=}
   ;;
@@ -108,14 +111,20 @@ do
     exit 0
   ;;
   *)
-    if [ $EBUILD_COMPAT -ne 1 ]; then
-      echo "Unknown argument: $arg"
-      print_usage
-      exit 1
-    fi
+    ERRORS="$ERRORS $arg"
   ;;
   esac
 done
+
+if [ -n "$ERRORS" ] && [ $EBUILD_COMPAT -ne 1 ]; then
+  for error in $ERRORS; do
+    echo "Unknown argument: $error"
+  done
+
+  print_usage
+  exit 1
+fi
+
 
 rm -f include.mk
 case $TARGET in 
